name: Add Two Numbers

on:
  workflow_dispatch:
    inputs:
      number1:
        description: 'First number'
        required: true
        default: '0'
      number2:
        description: 'Second number'
        required: true
        default: '0'

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Add numbers
        run: |
          echo "First Number: ${{ github.event.inputs.number1 }}"
          echo "Second Number: ${{ github.event.inputs.number2 }}"
          result=$(( ${{ github.event.inputs.number1 }} + ${{ github.event.inputs.number2 }} ))
          echo "Sum is: $result"
